name: CI

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==2.3.0 ruff openpyxl

      - name: Run ruff
        run: |
          echo "Running ruff (shows linter output in CI logs)"
          ruff .

      - name: Run analysis script
        run: |
          echo "Running execute.py and capturing output to result.json"
          python execute.py > result.json

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: result.json

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
